cards:
- name: Rules Reference
  rules:
    '67.1':
      rule: Each unit that a player can produce has a cost value presented on its
        faction sheet or technology card. To produce a unit, a player must spend a
        number of resources equal to or greater than the cost value of the unit they
        are producing.
      subrules:
        67.1.1:
          rule: Spent resources must come from planets or trade goods that are controlled
            by the player who is producing the units.
        67.1.2:
          rule: Any resources spent in excess of a unit’s cost are lost.
        67.1.3:
          rule: If a player is producing multiple units at a time, that player can
            add the cost of each unit they are producing to create a total cost before
            they spend any resources.
    '67.2':
      rule: If the cost is accompanied by two icons – typically for fighters and infantry
        – a player produces two of that unit for that cost.
      subrules:
        67.2.1:
          rule: Each of the two units counts toward the total number of units a player
            can produce.
        67.2.2:
          rule: A player can choose to produce only one unit; however, they must still
            pay the entire cost.
    '67.3':
      rule: When a player produces a unit through the use of their units’ Production
        abilities during a tactical action, that player follows the rules of the Production
        ability to determine where in the active system the units can be placed.
    '67.4':
      rule: When a player produces a unit through an ability outside of the tactical
        action, that ability will state how many units that player can produce and
        where that player can place those units.
      subrules:
        67.4.1:
          rule: A player cannot produce a unit on a planet they do not control.
        67.4.2:
          rule: If an ability allows a player to produce a unit in a system, they
            may produce that unit in the space area or on a planet they control in
            that system.
    '67.5':
      rule: A player is limited by the number of units in their reinforcements.
      subrules:
        67.5.1:
          rule: If a player cannot produce a unit because it is not in their reinforcements,
            that player can remove a unit from any system that does not contain one
            of their command tokens and place that unit in their reinforcements. Then,
            that player can produce that unit. A player can remove any number of their
            units in this way; however, any units that are removed must be produced
            immediately.
        67.5.2:
          rule: When producing a fighter or infantry unit, a player can use a fighter
            or infantry token, as appropriate, from the supply instead of a plastic
            piece.
    '67.6':
      rule: A player cannot produce ships in a system that contains other players’
        ships.
      subrules:
        67.6.1:
          rule: Ground forces can still be produced.
- name: Notes
  rules:
    '1':
      rule: Whenever a unit is produced, its cost must be paid, unless the effect
        that is producing the unit explicitly says otherwise.
    '2':
      rule: A player cannot produce one fighter and one infantry for one resource.
    '3':
      rule: If an effect allows a player to produce a unit of a specific type, then
        factional variations do not prevent that player from producing that type of
        unit.
    '4':
      rule: If a player removes a unit in order to place it, because they have none
        of that unit type in their reinforcements, that unit is placed undamaged.
- name: Related Topics
