cards:
- name: Rules Reference
  rules:
    '23.1':
      rule: 'Dice: Dice are limitless. If a player needs to roll more dice than the
        game provides, that player should roll as many as possible, record the results,
        and then reroll dice as necessary.'
    '23.2':
      rule: 'Tokens: Tokens are limited to those included in the game, except for
        the following:'
    '23.3':
      rule: If any of the above tokens are depleted, players can use a suitable substitute,
        such as a coin or bead.
    '23.4':
      rule: 'Units: Units are limited to those included in the game, except for fighters
        and ground forces.'
      subrules:
        23.4.1:
          rule: When a player would place a unit, if there are none of that type left
            in their reinforcements, that player can remove a unit from any system
            that does not contain one of their command tokens and place that unit
            in their reinforcements. A player can remove any number of their units
            in this way; however, any units that are removed must be placed immediately.
            Abilities cannot force a player to remove and place a unit in this manner.
        23.4.2:
          rule: When producing a fighter or infantry unit, a player can use a fighter
            or infantry token, as appropriate, from the supply instead of a plastic
            piece. These tokens must be accompanied by at least one plastic piece
            of the same type; players can swap infantry and fighter tokens for plastic
            pieces at any time.
    '23.5':
      rule: 'Cards: When a deck is depleted, players shuffle the deck’s discard pile
        and place it facedown to create a new deck.'
- name: Notes
  rules:
    '1':
      rule: As each player only has ten plastic fighter figures and twelve plastic
        infantry figures, a player cannot have fighters in more than ten systems,
        and cannot have infantry on more than twelve planets or being carried in more
        than twelve space areas, or any combination thereof.
    '2':
      rule: Players may also swap infantry and fighter plastic pieces for tokens at
        any time.
    '3':
      rule: Players may swap between three value tokens and one value tokens as desired.
    '4':
      rule: A player may only resolve a deploy ability to place a unit that is in
        their reinforcements. A player cannot remove a unit from the board to use
        its deploy ability.
    '5':
      rule: Each faction has sixteen command and seventeen control tokens included
        in the game.
    '6':
      rule: When a discard pile is shuffled to form a new deck, any cards that have
        been purged are not included.
    '7':
      rule: If a player removes a unit in order to place it, because they have none
        of that unit type in their reinforcements, that unit is placed undamaged.
    '8':
      rule: If a player is instructed to “replace” one unit with another, and they
        have none of the replacement unit type in their reinforcements, they may remove
        a unit of that type from any system that does not contain one of their command
        tokens and place that unit instead.
- name: Related Topics
