cards:
- name: Rules Reference
  rules:
    '50.1':
      rule: The leader slots of the leader sheet are where players place their three
        leader cards during setup. Each slot displays the name of the type of leader
        that is placed in that slot (agent, commander, and hero) as well as a symbol
        in the upper–right that helps players quickly determine which side of those
        leaders begins the game faceup.
      subrules:
        50.1.1:
          rule: The sides of the leader cards that display one (agent), two (commander),
            or three (hero) hash marks, respectively, begin the game faceup.
    '50.2':
      rule: The mech slot of the leader sheet is where players place their mech unit
        cards during setup.
    '50.3':
      rule: Players who are familiar with the game can hide the quick reference by
        placing that portion of the leader sheet under their faction sheets.
- name: Notes
- name: Related Topics
