cards:
- name: Rules Reference
  rules:
    '100.1':
      rule: The wormhole nexus begins the game in play with its inactive side up.
      subrules:
        100.1.1:
          rule: The inactive side of the wormhole nexus contains a gamma wormhole.
            The active side of the wormhole nexus contains an alpha, beta, and gamma
            wormhole.
        100.1.2:
          rule: The wormhole nexus is treated as part of the game board.
        100.1.3:
          rule: The wormhole nexus is on the edge of the game board.
    '100.2':
      rule: After a player moves or places a unit into the wormhole nexus, or gains
        control of the planet Mallice, that player flips the wormhole nexus to its
        active side.
      subrules:
        100.2.1:
          rule: When a ship moves into the wormhole nexus, the nexus becomes active
            at the end of the Movement step.
- name: Notes
  rules:
    '1':
      rule: The wormhole nexus will flip if a unit exists in the system while inactive,
        even if that unit did not move through a gamma wormhole.
    '2':
      rule: As the wormhole nexus becomes active at the end of the Movement step,
        only units with the Deep Space Cannon ability in systems containing a gamma
        wormhole will be able to produce hits during the Space Cannon Offense step
        during that action.
    '3':
      rule: If the Creuss player moves their Hil Colish flagship into the inactive
        wormhole nexus, the wormhole nexus will not flip before they move any other
        ships. Any other ships they wish to move into the wormhole nexus must do so
        via either a delta wormhole or a gamma wormhole, unless the Creuss player
        is utilizing the ability of their agent, Emissary Taivra.
    '4':
      rule: Any units and tokens on the inactive side are transferred to the active
        side when the wormhole nexus flips.
    '5':
      rule: A ship in the wormhole will single–handedly qualify for the Become the
        Gatekeeper objective.
- name: Related Topics
