name: tirules
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^15.0.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/rules/
    - assets/rules/component_notes/
    - assets/rules/faction_notes/
    - assets/rules/rule_topics/
